version: '3.8'

services:
  app:
    image: todo-backend
    build: .              # Declares where to build if image is not found
    ports:                # Declares the ports to publish
      - 3000:3000
